services:
  frontend:
    container_name: testcase_dev_frontend

  backend:
    container_name: testcase_dev_backend

  postgres:
    container_name: testcase_dev_postgres

  redis:
    container_name: testcase_dev_redis
