FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

RUN corepack enable

COPY backend/package.json backend/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY backend/ ./
RUN pnpm prisma:generate

EXPOSE 3000

CMD ["pnpm", "start:dev"]