[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm prisma:generate",
  "pnpm build"
]

[start]
cmd = "npx prisma migrate deploy && node dist/main.js"
