/** 写入 admin_audit_logs.action，便于检索与前端展示 */
export const ADMIN_AUDIT_ACTION = {
  RESET_PASSWORD: 'ADMIN_RESET_PASSWORD',
  UPDATE_ROLE: 'ADMIN_UPDATE_ROLE',
  SETTINGS_AI_MODEL_CREATE: 'SETTINGS_AI_MODEL_CREATE',
  SETTINGS_AI_MODEL_UPDATE: 'SETTINGS_AI_MODEL_UPDATE',
  SETTINGS_AI_MODEL_DELETE: 'SETTINGS_AI_MODEL_DELETE',
  SETTINGS_AI_MODEL_SET_DEFAULT: 'SETTINGS_AI_MODEL_SET_DEFAULT',
  SETTINGS_MULTIMODAL_CONFIG_UPDATE: 'SETTINGS_MULTIMODAL_CONFIG_UPDATE',
} as const
